config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions
  resources :contacts
  resources :projects
  
  resources :users, except: :index do
    member do
      get :activate
      get :following, :followers
    end
  end
  
  resources :posts
  resources :comments, except: [:new, :edit]

  #get "/feed", to: "application#feed"

  get '/login', to: 'user_sessions#new', :as => :login
  delete '/logout' => 'user_sessions#destroy', :as => :logout
  root "application#home"
  get "/discuss", to: "application#discuss"
  get  '/signup',  to: 'users#new'
  get "/search", to: "application#search"
 # get "/about", to: "application#about"
  resources :relationships,       only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/user.rb
class User < ApplicationRecord 
  include Likeable
  include Followable
  
  has_one_attached :avatar

  has_many :active_relationships, class_name:  "Relationship",
                                    foreign_key: "follower_id",
                                          dependent:   :destroy

  # Fix this problem, for now only users can be followed
  has_many :following, through: :active_relationships, source: :followable, source_type: "User"


  has_many :projects, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  authenticates_with_sorcery!
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX }

  validates :password, length: { minimum: 8 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }    
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }


  def follow(user)
    following << user
  end

  def unfollow(user)
    following.delete(user)
  end
  
  def following?(other_user)
    following.include?(other_user)
  end

  def recommended?(post)
    weight = 0
    likes.where(likeable_type: "Post").each do |like|
      weight += like.likeable.similarity(post)
    end
    weight / 1.2 
  end

  def title
    username
  end

  def relative_url 
    "/users/#{id}"
  end

  include AlgoliaSearch
  algoliasearch index_name: Rails.application.config.algolia_index, id: :algolia_id do
    attributes :title, :like_count, :relative_url

    searchableAttributes ['title']
    customRanking ['desc(like_count)']
  end
  
  ## Define custom methods so that records can be indexed on same indice with algolia
  private
    def algolia_id
      "user_#{id}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  skip_before_action :require_login, only: [:index, :new, :create, :show, :activate, :following, :followers]  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :require_no_user, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page params[:page]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
   # @user.custom_css = Sanitize::CSS.stylesheet(@user.custom_css, Sanitize::Config::RELAXED)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created. Please activate your account to log in." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end


  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      redirect_to(:login, :notice => 'User was successfully activated.')
    else
      not_authenticated
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(40)
    render 'relationships/show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(40)
    render 'relationships/show_follow'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation, :github, :avatar)
    end

    def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        flash[:error] = "You don't have the permissions to edit that user."
        redirect_back fallback_location: root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<% if user.avatar.attached? %>
  <%= image_tag user.avatar.variant(resize_to_limit: [100, 100]), class: "avatar", alt: "user-avatar" %>
<% elsif !user.github.blank? %>
    <img src="https://github.com/<%= user.github %>.png" width="100" height="100"  alt="profile pic" class="avatar">
  <% else %> 
    <svg data-jdenticon-value="<%= user.username %>" width="100" height="100" class="avatar"></svg>
  <% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render "shared/error_messages", object: user %>
  <div class="field">
    <%= form.text_field :username, placeholder: "Username" %>
  </div>
  <div class="field">
    <%= form.email_field :email, placeholder: "Email" %>
  </div>
  <% unless current_page?(:action => "new") %>
    <div class="contact-line"></div>
    <div class="field">
    <%= form.text_field :github, placeholder: "Github username" %>
    </div>
    <div class="field">
      <%= form.file_field :avatar, style:"display: none" %>
      <div class="random">
        <%= render "avatar", user: @user %>
        <p class="btn-white">Avatar</p>
      </div>
    </div>
  <% end %>
  <div class="contact-line"></div>
  <div class="field">
    <%= form.password_field :password, placeholder: "Password" %>
  </div>

  <div class="field">
    <%= form.password_field :password_confirmation, placeholder: "Password Confirmation" %>
  </div>
  <div class="contact-line"></div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_pack_tag "user-avatar" %>

app/views/users/_user.html.erb
<li style="text-align: center;">
  <%= render "avatar", user: user %>
  <%= link_to user.username, user_path(user), style: "color: #c9485b; display: block" %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, "Edit Profile") %>
<div class="user_info">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<%= provide(:title, "Users") %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<section class="stats">
<%= render 'shared/stats' %>
</section>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= provide(:title, "Sign Up") %>
<div class="user_info">
<h1>New User</h1>
<p>Sign up through Github</p>
<%= render "shared/oauth" %>

<p>Or through the site</p>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.username) %>

<div class="user-cont">
<div class='about-user'>
<%= render 'relationships/follow_form', object: @user if current_user %>

  <h1><%= @user.username %></h1>
  <% if !@user.github.blank? %> 
    <a href="https://github.com/<%= @user.github %>" target="_blank" rel="noopener" style="margin: 10px 0px" class="fab fa-github"></a>
  <% end %>

  <%= render "shared/stats" %>
  <h2>Projects</h2>
  <% @user.projects.each do |project| %>
    <h2><%= link_to project.name, project_url(project)  %></h2>
  <% end %>
  <br>
  <% if @user == current_user %>
    <%= link_to 'Edit', edit_user_path(@user), class: "btn-white" %>
  <% end %>
</div>
<div class="posts">
  <%= render "avatar", user: @user %>
  <br>
  <% if @user.posts.any? %>
    <h3>Posts (<%= @user.posts.count %>)</h3>
    <ul>
      <%= render @posts %>
    </ul>
    <%= paginate @posts %>
  <% else %>
    <p>This user hasn't posted anything yet</p>
    <%= image_tag "empty.svg", width: "300" %>
  <% end %>
</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
<div class="row">
    <section class="user_info">
      <h1><%= @user.username %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>