config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions
  resources :contacts
  resources :projects
  
  resources :users, except: :index do
    member do
      get :activate
      get :following, :followers
    end
  end
  
  resources :posts
  resources :comments, except: [:new, :edit]

  #get "/feed", to: "application#feed"

  get '/login', to: 'user_sessions#new', :as => :login
  delete '/logout' => 'user_sessions#destroy', :as => :logout
  root "application#home"
  get "/discuss", to: "application#discuss"
  get  '/signup',  to: 'users#new'
  get "/search", to: "application#search"
 # get "/about", to: "application#about"
  resources :relationships,       only: [:create, :destroy]
  resources :likes,       only: [:create, :destroy]

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/project.rb
class Project < ApplicationRecord
  require 'uri'
  include Followable

  has_one_attached :logo
  
  belongs_to :user
  has_many :posts
  
  validates :description, presence: true
  validates :user_id, presence: true
  validates :url, format: { with: URI.regexp }, allow_blank: true

  
  ## Define custom methods so that records can be indexed on same indice with algolia
  def like_count
    follower_count
  end

  def relative_url 
    "/projects/#{id}"
  end

  def title
    name
  end

  def body
    description
  end

  def html_processed
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
    ActionController::Base.helpers.sanitize(markdown.render(body))
  end

  include AlgoliaSearch
  algoliasearch index_name: Rails.application.config.algolia_index, id: :algolia_id do
    attributes :title, :body, :like_count, :relative_url

    searchableAttributes ['name', 'unordered(body)']
    customRanking ['desc(like_count)']
  end
  
  private
    def algolia_id
      "project_#{id}"
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :require_login, except: [:show, :index]
    before_action :correct_author, only: [:update, :edit, :destroy]
    before_action :get_post, except: [:create, :new, :index]

    def index
      @projects = Kaminari.paginate_array(Project.all.sort_by { |project| project.created_at }).page(params[:page]).per(6)
    end

    def create
        @project = current_user.projects.build(project_params)
        respond_to do |format|
          if @project.save
            format.html { redirect_to @project, notice: 'Project was successfully created.' }
            format.json { render :show, status: :ok, location: @project }
          else
            format.html { render :edit }
            format.json { render json: @project.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
        respond_to do |format|
          if @project.update(project_params)
            format.html { redirect_to @project, notice: 'Project was successfully updated.' }
            format.json { render :show, status: :ok, location: @project }
          else
            format.html { render :edit }
            format.json { render json: @project.errors, status: :unprocessable_entity }
          end
        end
      end

    def edit
    end

    def destroy
        @project.destroy
        flash[:notice] = "Project deleted"
        redirect_back fallback_location: @project.user
    end

    def show
      @post = Post.new
    end

    def new
        @project = Project.new
    end

    def correct_author
      @project = Project.find(params[:id])
      unless @project.user == current_user
        flash[:error] = "You don't have the permissions to edit that project."
        redirect_to @project
      end
    end

    def get_post
      @project = Project.find(params[:id])
    end

    private 
        def project_params
            params.require(:project).permit(:name, :url, :source, :description, :logo)
        end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="project">
  <div class="project-info">
    <%= render "logo", project: @project %>
    <div class="project-text">
      <h1><%= @project.name %></h1>
    </div>
  </div>
  <div class="project-form">
  <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <h3>Name</h3>
        <%= f.text_field :name %>
        <h3>Description</h2>
        <%= f.text_area :description, oninput:'this.style.height = "";this.style.height = this.scrollHeight + "px"' %>
        <h3>Website</h3>
        <%= f.url_field :url %>
        <h3>Source Code URL</h3>
        <%= f.url_field :source %>
        <%= f.file_field :logo, style: "display: none" %>
      </div>
      <br>
      <%= f.submit "Post", class: "btn-red" %>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag "project-logo" %>
<script>
window.onload = function() {
  let textarea = document.getElementById("project_description")
  textarea.style.height = textarea.scrollHeight + "px"
}
</script>

app/views/projects/_logo.html.erb
<div class="project-logo-div">
<% if project.logo.attached? %>
  <%= image_tag project.logo, alt: "project-logo", width: "100", height: "100" %>
<% else %>
  <div class="project-identicon">
    <% identicon = project.new_record? ? "#{current_user.username}-project-#{current_user.projects.count}" : "#{project.user.username}-project-#{project.user.projects.index(project)}" %>
    <svg data-jdenticon-value="<%= identicon %>" width="100" height="100"></svg>
  </div>
<% end %>
</div>

app/views/projects/_project.html.erb
<div class="project">
<div class="project-mast">
    <div class="project-info">
      <div>
        <h1><%= link_to project.name, project.url, class: "white-link" %></h1>
        <div class="project-btns">
          <% if project.source != "" %>
            <a href="<%= project.source %>" target="_blank" rel="noopener" class="fab fa-github"></a>
          <% end %> 
          <% if project.url != "" %>
            <a href="<%= project.url %>" target="_blank" rel="noopener" class="fas fa-link"></a>
          <% end %>
          <% if project.user == current_user %>
            <a href="<%= edit_project_path(project) %>"><%= image_tag "edit.svg" %></a>
            <%= button_to "Delete", project, method: :delete, class: "btn-red"  %>
          <% end %>
        </div>
      </div>
      <%= render "logo", project: project %>
    </div>
    <div class="project-text">
      <p style="display: block;"><%= project.html_processed %></p>
    </div>
</div>
  <!--
  <div class="project-btns">
    <%= render 'relationships/follow_form', object: project if current_user %>
  </div>
  -->
</div>

app/views/projects/edit.html.erb
<%= provide(:title, "Editing #{@project.name}") %>

<%= render "form" %>

app/views/projects/index.html.erb
<%= provide(:title, "Projects") %>
<a href="/projects/new" class="btn-red" style="margin: 10px 110px; display: inline-block; font-size: 20px;">Add yours!</a>
<%= render @projects %>
<%= paginate @projects %>

app/views/projects/new.html.erb
<%= provide(:title, "New Project") %>

<%= render "form" %>

app/views/projects/show.html.erb
<%= provide(:title, @project.name) %>
  <%= render @project %>